In [347]:
import pandas as pd 
import numpy as np

In [348]:
df_present = pd.read_csv("pre_model_format_read.csv")
df_present

,Local ID,Grade_4_Present_Reading_ Percent_Score,Grade_4_last_year_Reading_Percent_Score,Grade_4_Practice2018_Reading_Percent Score,Grade_4_Practice2019_Reading_Percent_Score_x,Meal Status,Temp Lunch Status,Special Ed Indicator_No,Special Ed Indicator_Yes,LEP_First Year of Monitoring,LEP_LEP,LEP_Other Non-LEP Student,LEP_Second Year of Monitoring,Ethnicity_Asian,Ethnicity_Black/African American,Ethnicity_Hispanic,Continously_Enrolled_grade4_Null,Continously_Enrolled_grade4_Yes
0,931151,0.56,0.65,0.69,1.00,01 - Free,Null,1,0,0,1,0,0,0,0,1,1,0
1,966007,0.67,0.38,0.44,0.82,NaN,Null,1,0,0,1,0,0,0,0,1,1,0
2,324370,0.64,0.72,0.44,1.00,NaN,Null,1,0,0,0,1,0,0,1,0,1,0
3,952823,0.81,0.65,0.83,1.00,01 - Free,Null,1,0,0,0,0,1,0,0,1,0,1
4,931762,0.33,0.32,0.33,0.29,01 - Free,Null,1,0,0,1,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,924046,0.44,0.50,0.14,0.59,01 - Free,Null,1,0,0,1,0,0,0,0,1,0,1
108,948348,0.83,0.88,0.78,0.94,01 - Free,Null,1,0,0,0,1,0,0,0,1,0,1
109,950771,0.64,0.59,0.72,0.76,01 - Free,Y - Yes,1,0,0,0,1,0,0,1,0,0,1
110,948810,0.31,0.44,0.25,0.53,01 - Free,Null,1,0,0,0,1,0,0,1,0,0,1
111,324645,0.58,0.56,0.50,0.71,01 - Free,Null,1,0,0,1,0,0,0,0,1,1,0

In [349]:
#hot code meal status and temp lunch

#first convert missing values for meal status to null
values = {'Meal Status': "Null"}
df_present = df_present.fillna(value=values)

#then hotcode
df_new = pd.get_dummies(data=df_present,columns=["Meal Status"])
df_new


#hotcode temp lunch
df_new1 = pd.get_dummies(data=df_new,columns=["Temp Lunch Status"])
df_new1

#df_new2 = df_new1.astype(int)
#df_new2

,Local ID,Grade_4_Present_Reading_ Percent_Score,Grade_4_last_year_Reading_Percent_Score,Grade_4_Practice2018_Reading_Percent Score,Grade_4_Practice2019_Reading_Percent_Score_x,Special Ed Indicator_No,Special Ed Indicator_Yes,LEP_First Year of Monitoring,LEP_LEP,LEP_Other Non-LEP Student,...,Ethnicity_Asian,Ethnicity_Black/African American,Ethnicity_Hispanic,Continously_Enrolled_grade4_Null,Continously_Enrolled_grade4_Yes,Meal Status_01 - Free,Meal Status_02 - Reduced,Meal Status_Null,Temp Lunch Status_Null,Temp Lunch Status_Y - Yes
0,931151,0.56,0.65,0.69,1.00,1,0,0,1,0,...,0,0,1,1,0,1,0,0,1,0
1,966007,0.67,0.38,0.44,0.82,1,0,0,1,0,...,0,0,1,1,0,0,0,1,1,0
2,324370,0.64,0.72,0.44,1.00,1,0,0,0,1,...,0,1,0,1,0,0,0,1,1,0
3,952823,0.81,0.65,0.83,1.00,1,0,0,0,0,...,0,0,1,0,1,1,0,0,1,0
4,931762,0.33,0.32,0.33,0.29,1,0,0,1,0,...,0,0,1,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,924046,0.44,0.50,0.14,0.59,1,0,0,1,0,...,0,0,1,0,1,1,0,0,1,0
108,948348,0.83,0.88,0.78,0.94,1,0,0,0,1,...,0,0,1,0,1,1,0,0,1,0
109,950771,0.64,0.59,0.72,0.76,1,0,0,0,1,...,0,1,0,0,1,1,0,0,0,1
110,948810,0.31,0.44,0.25,0.53,1,0,0,0,1,...,0,1,0,0,1,1,0,0,1,0
111,324645,0.58,0.56,0.50,0.71,1,0,0,1,0,...,0,0,1,1,0,1,0,0,1,0

In [350]:
#fill in missing scores with average of the last scores
#dropped ID 309795 since it was missing all reading scores
#I did this manually in excel. Needs to be automated

In [351]:
#move first column to the end
cols = list(df_new1.columns.values) #Make a list of all of the columns in the df
cols.pop(cols.index('Grade_4_Present_Reading_ Percent_Score')) #Remove b from list
df_new2 = df_new1[cols+['Grade_4_Present_Reading_ Percent_Score']] #Create new dataframe with columns in the order you want
len(df_new2.columns)
df_new2

,Local ID,Grade_4_last_year_Reading_Percent_Score,Grade_4_Practice2018_Reading_Percent Score,Grade_4_Practice2019_Reading_Percent_Score_x,Special Ed Indicator_No,Special Ed Indicator_Yes,LEP_First Year of Monitoring,LEP_LEP,LEP_Other Non-LEP Student,LEP_Second Year of Monitoring,...,Ethnicity_Black/African American,Ethnicity_Hispanic,Continously_Enrolled_grade4_Null,Continously_Enrolled_grade4_Yes,Meal Status_01 - Free,Meal Status_02 - Reduced,Meal Status_Null,Temp Lunch Status_Null,Temp Lunch Status_Y - Yes,Grade_4_Present_Reading_ Percent_Score
0,931151,0.65,0.69,1.00,1,0,0,1,0,0,...,0,1,1,0,1,0,0,1,0,0.56
1,966007,0.38,0.44,0.82,1,0,0,1,0,0,...,0,1,1,0,0,0,1,1,0,0.67
2,324370,0.72,0.44,1.00,1,0,0,0,1,0,...,1,0,1,0,0,0,1,1,0,0.64
3,952823,0.65,0.83,1.00,1,0,0,0,0,1,...,0,1,0,1,1,0,0,1,0,0.81
4,931762,0.32,0.33,0.29,1,0,0,1,0,0,...,0,1,0,1,1,0,0,1,0,0.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,924046,0.50,0.14,0.59,1,0,0,1,0,0,...,0,1,0,1,1,0,0,1,0,0.44
108,948348,0.88,0.78,0.94,1,0,0,0,1,0,...,0,1,0,1,1,0,0,1,0,0.83
109,950771,0.59,0.72,0.76,1,0,0,0,1,0,...,1,0,0,1,1,0,0,0,1,0.64
110,948810,0.44,0.25,0.53,1,0,0,0,1,0,...,1,0,0,1,1,0,0,1,0,0.31
111,324645,0.56,0.50,0.71,1,0,0,1,0,0,...,0,1,1,0,1,0,0,1,0,0.58

In [352]:
X = df_new2.iloc[:, 1:20]
y = df_new2['Grade_4_Present_Reading_ Percent_Score']

In [353]:
X

,Grade_4_last_year_Reading_Percent_Score,Grade_4_Practice2018_Reading_Percent Score,Grade_4_Practice2019_Reading_Percent_Score_x,Special Ed Indicator_No,Special Ed Indicator_Yes,LEP_First Year of Monitoring,LEP_LEP,LEP_Other Non-LEP Student,LEP_Second Year of Monitoring,Ethnicity_Asian,Ethnicity_Black/African American,Ethnicity_Hispanic,Continously_Enrolled_grade4_Null,Continously_Enrolled_grade4_Yes,Meal Status_01 - Free,Meal Status_02 - Reduced,Meal Status_Null,Temp Lunch Status_Null,Temp Lunch Status_Y - Yes
0,0.65,0.69,1.00,1,0,0,1,0,0,0,0,1,1,0,1,0,0,1,0
1,0.38,0.44,0.82,1,0,0,1,0,0,0,0,1,1,0,0,0,1,1,0
2,0.72,0.44,1.00,1,0,0,0,1,0,0,1,0,1,0,0,0,1,1,0
3,0.65,0.83,1.00,1,0,0,0,0,1,0,0,1,0,1,1,0,0,1,0
4,0.32,0.33,0.29,1,0,0,1,0,0,0,0,1,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,0.50,0.14,0.59,1,0,0,1,0,0,0,0,1,0,1,1,0,0,1,0
108,0.88,0.78,0.94,1,0,0,0,1,0,0,0,1,0,1,1,0,0,1,0
109,0.59,0.72,0.76,1,0,0,0,1,0,0,1,0,0,1,1,0,0,0,1
110,0.44,0.25,0.53,1,0,0,0,1,0,0,1,0,0,1,1,0,0,1,0
111,0.56,0.50,0.71,1,0,0,1,0,0,0,0,1,1,0,1,0,0,1,0

In [354]:
y

0      0.56
1      0.67
2      0.64
3      0.81
4      0.33
       ...
107    0.44
108    0.83
109    0.64
110    0.31
111    0.58
Name: Grade_4_Present_Reading_ Percent_Score, Length: 112, dtype: float64

In [355]:
from sklearn.model_selection import train_test_split

In [356]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 10)

In [357]:
X_train

,Grade_4_last_year_Reading_Percent_Score,Grade_4_Practice2018_Reading_Percent Score,Grade_4_Practice2019_Reading_Percent_Score_x,Special Ed Indicator_No,Special Ed Indicator_Yes,LEP_First Year of Monitoring,LEP_LEP,LEP_Other Non-LEP Student,LEP_Second Year of Monitoring,Ethnicity_Asian,Ethnicity_Black/African American,Ethnicity_Hispanic,Continously_Enrolled_grade4_Null,Continously_Enrolled_grade4_Yes,Meal Status_01 - Free,Meal Status_02 - Reduced,Meal Status_Null,Temp Lunch Status_Null,Temp Lunch Status_Y - Yes
26,0.350,0.39,0.59,1,0,0,1,0,0,0,0,1,1,0,1,0,0,1,0
104,0.880,0.75,1.00,1,0,0,0,1,0,0,0,1,0,1,1,0,0,1,0
59,0.385,0.36,0.41,0,1,0,0,1,0,0,0,1,0,1,1,0,0,1,0
98,0.615,0.58,0.65,1,0,0,0,0,1,0,0,1,0,1,1,0,0,1,0
3,0.650,0.83,1.00,1,0,0,0,0,1,0,0,1,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,0.680,0.69,0.76,1,0,1,0,0,0,0,0,1,1,0,1,0,0,1,0
64,0.470,0.31,0.18,0,1,0,0,1,0,0,1,0,0,1,1,0,0,1,0
15,0.850,0.83,0.82,1,0,0,0,0,1,0,0,1,0,1,1,0,0,1,0
100,0.450,0.31,0.59,1,0,0,0,1,0,0,1,0,1,0,1,0,0,1,0
9,0.575,0.44,0.71,1,0,0,1,0,0,0,0,1,1,0,1,0,0,1,0

In [358]:
X_test

,Grade_4_last_year_Reading_Percent_Score,Grade_4_Practice2018_Reading_Percent Score,Grade_4_Practice2019_Reading_Percent_Score_x,Special Ed Indicator_No,Special Ed Indicator_Yes,LEP_First Year of Monitoring,LEP_LEP,LEP_Other Non-LEP Student,LEP_Second Year of Monitoring,Ethnicity_Asian,Ethnicity_Black/African American,Ethnicity_Hispanic,Continously_Enrolled_grade4_Null,Continously_Enrolled_grade4_Yes,Meal Status_01 - Free,Meal Status_02 - Reduced,Meal Status_Null,Temp Lunch Status_Null,Temp Lunch Status_Y - Yes
103,0.880,0.81,0.88,1,0,1,0,0,0,1,0,0,0,1,0,1,0,1,0
91,0.710,0.53,0.59,1,0,1,0,0,0,0,0,1,0,1,1,0,0,1,0
75,0.880,0.97,0.94,1,0,0,0,0,1,1,0,0,1,0,0,0,1,1,0
48,0.710,0.17,0.53,1,0,0,1,0,0,0,0,1,0,1,1,0,0,1,0
53,0.290,0.28,0.29,0,1,0,0,1,0,0,0,1,0,1,1,0,0,1,0
52,0.370,0.33,0.41,1,0,0,0,1,0,0,1,0,1,0,1,0,0,1,0
38,0.650,0.39,0.88,1,0,0,0,1,0,0,0,1,0,1,1,0,0,0,1
42,0.740,0.64,0.76,1,0,0,0,1,0,0,0,1,0,1,0,0,1,1,0
2,0.720,0.44,1.00,1,0,0,0,1,0,0,1,0,1,0,0,0,1,1,0
39,0.905,0.81,1.00,1,0,0,0,0,1,0,0,1,0,1,1,0,0,1,0
45,0.660,0.50,0.82,1,0,1,0,0,0,0,0,1,0,1,1,0,0,0,1
76,0.910,0.92,0.88,1,0,0,0,1,0,1,0,0,0,1,1,0,0,1,0
90,0.675,0.64,0.71,1,0,0,1,0,0,0,0,1,1,0,1,0,0,1,0
81,0.620,0.72,0.88,1,0,0,0,0,1,0,0,1,0,1,1,0,0,0,1
1,0.380,0.44,0.82,1,0,0,1,0,0,0,0,1,1,0,0,0,1,1,0
10,0.650,0.61,0.88,1,0,0,0,0,1,0,0,1,0,1,1,0,0,0,1
37,0.940,0.89,0.94,1,0,0,0,1,0,1,0,0,0,1,0,0,1,1,0
47,0.680,0.58,0.24,1,0,0,1,0,0,0,0,1,0,1,1,0,0,1,0
79,0.790,0.67,0.94,1,0,0,0,1,0,0,0,1,1,0,1,0,0,1,0
41,0.885,0.83,0.94,1,0,0,0,0,1,0,0,1,0,1,1,0,0,0,1
35,0.910,0.83,0.71,1,0,0,0,0,1,0,0,1,0,1,1,0,0,1,0
19,0.760,0.42,0.82,1,0,0,0,1,0,0,0,1,0,1,1,0,0,1,0
14,0.350,0.14,0.47,0,1,0,0,1,0,0,1,0,0,1,1,0,0,0,1

In [359]:
y_test

103    0.94
91     0.67
75     0.97
48     0.47
53     0.19
52     0.44
38     0.61
42     0.72
2      0.64
39     0.92
45     0.69
76     0.92
90     0.50
81     0.67
1      0.67
10     0.86
37     0.97
47     0.44
79     0.89
41     0.78
35     0.89
19     0.75
14     0.22
Name: Grade_4_Present_Reading_ Percent_Score, dtype: float64

In [360]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()

In [361]:
clf.fit(X_train,y_train)

LinearRegression()

In [362]:
y_pred = clf.predict(X_test)

In [363]:
clf.score(X_test, y_test)

0.7600052206683028

In [364]:
df1 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
#df1=df1['Actual']*100
#df1
df1['Actual']=df1['Actual']*100
df1['Predicted']=df1['Predicted']*100
df1

     Actual  Predicted
103    94.0  85.915876
91     67.0  53.485278
75     97.0  92.597323
48     47.0  49.304910
53     19.0  42.454805
52     44.0  44.083140
38     61.0  75.014902
42     72.0  68.738480
2      64.0  74.657428
39     92.0  93.794106
45     69.0  62.245474
76     92.0  93.399436
90     50.0  59.915304
81     67.0  80.674559
1      67.0  52.173294
10     86.0  80.304330
37     97.0  91.116304
47     44.0  38.409735
79     89.0  82.663231
41     78.0  89.699012
35     89.0  80.187400
19     75.0  75.566791
14     22.0  47.999982

In [365]:
df3 = pd.concat([df1,X_test], axis=1)

In [366]:
df3['Grade_4_last_year_Reading_Percent_Score']=df3['Grade_4_last_year_Reading_Percent_Score']*100
df3['Grade_4_Practice2018_Reading_Percent Score']=df3['Grade_4_Practice2018_Reading_Percent Score']*100
df3['Grade_4_Practice2019_Reading_Percent_Score_x']=df3['Grade_4_Practice2019_Reading_Percent_Score_x']*100
df3

,Actual,Predicted,Grade_4_last_year_Reading_Percent_Score,Grade_4_Practice2018_Reading_Percent Score,Grade_4_Practice2019_Reading_Percent_Score_x,Special Ed Indicator_No,Special Ed Indicator_Yes,LEP_First Year of Monitoring,LEP_LEP,LEP_Other Non-LEP Student,...,Ethnicity_Asian,Ethnicity_Black/African American,Ethnicity_Hispanic,Continously_Enrolled_grade4_Null,Continously_Enrolled_grade4_Yes,Meal Status_01 - Free,Meal Status_02 - Reduced,Meal Status_Null,Temp Lunch Status_Null,Temp Lunch Status_Y - Yes
103,94.0,85.915876,88.0,81.0,88.0,1,0,1,0,0,...,1,0,0,0,1,0,1,0,1,0
91,67.0,53.485278,71.0,53.0,59.0,1,0,1,0,0,...,0,0,1,0,1,1,0,0,1,0
75,97.0,92.597323,88.0,97.0,94.0,1,0,0,0,0,...,1,0,0,1,0,0,0,1,1,0
48,47.0,49.304910,71.0,17.0,53.0,1,0,0,1,0,...,0,0,1,0,1,1,0,0,1,0
53,19.0,42.454805,29.0,28.0,29.0,0,1,0,0,1,...,0,0,1,0,1,1,0,0,1,0
52,44.0,44.083140,37.0,33.0,41.0,1,0,0,0,1,...,0,1,0,1,0,1,0,0,1,0
38,61.0,75.014902,65.0,39.0,88.0,1,0,0,0,1,...,0,0,1,0,1,1,0,0,0,1
42,72.0,68.738480,74.0,64.0,76.0,1,0,0,0,1,...,0,0,1,0,1,0,0,1,1,0
2,64.0,74.657428,72.0,44.0,100.0,1,0,0,0,1,...,0,1,0,1,0,0,0,1,1,0
39,92.0,93.794106,90.5,81.0,100.0,1,0,0,0,0,...,0,0,1,0,1,1,0,0,1,0
45,69.0,62.245474,66.0,50.0,82.0,1,0,1,0,0,...,0,0,1,0,1,1,0,0,0,1
76,92.0,93.399436,91.0,92.0,88.0,1,0,0,0,1,...,1,0,0,0,1,1,0,0,1,0
90,50.0,59.915304,67.5,64.0,71.0,1,0,0,1,0,...,0,0,1,1,0,1,0,0,1,0
81,67.0,80.674559,62.0,72.0,88.0,1,0,0,0,0,...,0,0,1,0,1,1,0,0,0,1
1,67.0,52.173294,38.0,44.0,82.0,1,0,0,1,0,...,0,0,1,1,0,0,0,1,1,0
10,86.0,80.304330,65.0,61.0,88.0,1,0,0,0,0,...,0,0,1,0,1,1,0,0,0,1
37,97.0,91.116304,94.0,89.0,94.0,1,0,0,0,1,...,1,0,0,0,1,0,0,1,1,0
47,44.0,38.409735,68.0,58.0,24.0,1,0,0,1,0,...,0,0,1,0,1,1,0,0,1,0
79,89.0,82.663231,79.0,67.0,94.0,1,0,0,0,1,...,0,0,1,1,0,1,0,0,1,0
41,78.0,89.699012,88.5,83.0,94.0,1,0,0,0,0,...,0,0,1,0,1,1,0,0,0,1
35,89.0,80.187400,91.0,83.0,71.0,1,0,0,0,0,...,0,0,1,0,1,1,0,0,1,0
19,75.0,75.566791,76.0,42.0,82.0,1,0,0,0,1,...,0,0,1,0,1,1,0,0,1,0
14,22.0,47.999982,35.0,14.0,47.0,0,1,0,0,1,...,0,1,0,0,1,1,0,0,0,1

In [367]:

df3['abs_diff'] = abs(df3['Actual'] - df3['Predicted'])
df3

,Actual,Predicted,Grade_4_last_year_Reading_Percent_Score,Grade_4_Practice2018_Reading_Percent Score,Grade_4_Practice2019_Reading_Percent_Score_x,Special Ed Indicator_No,Special Ed Indicator_Yes,LEP_First Year of Monitoring,LEP_LEP,LEP_Other Non-LEP Student,...,Ethnicity_Black/African American,Ethnicity_Hispanic,Continously_Enrolled_grade4_Null,Continously_Enrolled_grade4_Yes,Meal Status_01 - Free,Meal Status_02 - Reduced,Meal Status_Null,Temp Lunch Status_Null,Temp Lunch Status_Y - Yes,abs_diff
103,94.0,85.915876,88.0,81.0,88.0,1,0,1,0,0,...,0,0,0,1,0,1,0,1,0,8.084124
91,67.0,53.485278,71.0,53.0,59.0,1,0,1,0,0,...,0,1,0,1,1,0,0,1,0,13.514722
75,97.0,92.597323,88.0,97.0,94.0,1,0,0,0,0,...,0,0,1,0,0,0,1,1,0,4.402677
48,47.0,49.304910,71.0,17.0,53.0,1,0,0,1,0,...,0,1,0,1,1,0,0,1,0,2.304910
53,19.0,42.454805,29.0,28.0,29.0,0,1,0,0,1,...,0,1,0,1,1,0,0,1,0,23.454805
52,44.0,44.083140,37.0,33.0,41.0,1,0,0,0,1,...,1,0,1,0,1,0,0,1,0,0.083140
38,61.0,75.014902,65.0,39.0,88.0,1,0,0,0,1,...,0,1,0,1,1,0,0,0,1,14.014902
42,72.0,68.738480,74.0,64.0,76.0,1,0,0,0,1,...,0,1,0,1,0,0,1,1,0,3.261520
2,64.0,74.657428,72.0,44.0,100.0,1,0,0,0,1,...,1,0,1,0,0,0,1,1,0,10.657428
39,92.0,93.794106,90.5,81.0,100.0,1,0,0,0,0,...,0,1,0,1,1,0,0,1,0,1.794106
45,69.0,62.245474,66.0,50.0,82.0,1,0,1,0,0,...,0,1,0,1,1,0,0,0,1,6.754526
76,92.0,93.399436,91.0,92.0,88.0,1,0,0,0,1,...,0,0,0,1,1,0,0,1,0,1.399436
90,50.0,59.915304,67.5,64.0,71.0,1,0,0,1,0,...,0,1,1,0,1,0,0,1,0,9.915304
81,67.0,80.674559,62.0,72.0,88.0,1,0,0,0,0,...,0,1,0,1,1,0,0,0,1,13.674559
1,67.0,52.173294,38.0,44.0,82.0,1,0,0,1,0,...,0,1,1,0,0,0,1,1,0,14.826706
10,86.0,80.304330,65.0,61.0,88.0,1,0,0,0,0,...,0,1,0,1,1,0,0,0,1,5.695670
37,97.0,91.116304,94.0,89.0,94.0,1,0,0,0,1,...,0,0,0,1,0,0,1,1,0,5.883696
47,44.0,38.409735,68.0,58.0,24.0,1,0,0,1,0,...,0,1,0,1,1,0,0,1,0,5.590265
79,89.0,82.663231,79.0,67.0,94.0,1,0,0,0,1,...,0,1,1,0,1,0,0,1,0,6.336769
41,78.0,89.699012,88.5,83.0,94.0,1,0,0,0,0,...,0,1,0,1,1,0,0,0,1,11.699012
35,89.0,80.187400,91.0,83.0,71.0,1,0,0,0,0,...,0,1,0,1,1,0,0,1,0,8.812600
19,75.0,75.566791,76.0,42.0,82.0,1,0,0,0,1,...,0,1,0,1,1,0,0,1,0,0.566791
14,22.0,47.999982,35.0,14.0,47.0,0,1,0,0,1,...,1,0,0,1,1,0,0,0,1,25.999982

In [368]:
#convert back one hot encoding
#I did this manually in excel 
#export to excel
df3.to_csv(r'/Users/sukanyasravasti/LR_Reading_Grade4.csv', index = False)